In [177]:
# creating a dictonary

people = {
    "first":["corey","john","harry"],
    "last" : ["schafer","cena","potter"],
    "email":[ "coreyschafer@gmail.com","johncena@gmai;.com","harrypotter@gmail.com"]
             
}

In [178]:
people["email"] # to access information within dictonary

['coreyschafer@gmail.com', 'johncena@gmai;.com', 'harrypotter@gmail.com']

In [179]:
# creating a dataframe using a dictonary (people)
import pandas as pd

In [180]:
df = pd.DataFrame(people)
df

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com

In [181]:
df["email"] # to access information within dataframe ,
# better way to access

# outputs will be series object

0    coreyschafer@gmail.com
1        johncena@gmai;.com
2     harrypotter@gmail.com
Name: email, dtype: str

In [182]:
type(df["email"])

pandas.Series

In [183]:
# alternate way to access information within dataframe
df.email

0    coreyschafer@gmail.com
1        johncena@gmai;.com
2     harrypotter@gmail.com
Name: email, dtype: str

In [184]:
# to access multiple information
df[['email','last']] # list ['email','last'] is passed inside this bracket []
# i.e. df[list]. and list = ['email','last']

# NOTE - as we are accessing more than one info. the outputs will now not same as previoulsy as series 
# now the outputs will be dataframe and later we can extract information from them

                    email     last
0  coreyschafer@gmail.com  schafer
1      johncena@gmai;.com     cena
2   harrypotter@gmail.com   potter

In [185]:
df.columns # to access column info.

Index(['first', 'last', 'email'], dtype='str')

In [186]:
df.iloc[0] # to access row info having index 0 , i.e. 1st row
# & index here will be column name so we can clearly see what info. represnating what

first                     corey
last                    schafer
email    coreyschafer@gmail.com
Name: 0, dtype: str

In [187]:
df.iloc[[0,1]]
# to access multiple rows

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com

In [188]:
# To access row along with columns to
df.iloc[[0,1],2]

# here  first argument [0, 1] selects the rows, and the second argument 2 selects the third column (index 2)

0    coreyschafer@gmail.com
1        johncena@gmai;.com
Name: email, dtype: str

In [189]:
df.loc[0]

first                     corey
last                    schafer
email    coreyschafer@gmail.com
Name: 0, dtype: str

In [190]:
df.loc[[0,1]]

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com

In [191]:
# if we want only first column i.e. first name columns then 
df.loc[[0,1],"first"]
# error if we directly write df.loc[[0,1],0]

0    corey
1     john
Name: first, dtype: str

In [192]:
# if we want email and first name To
df.loc[[0,1],['first','email']]

   first                   email
0  corey  coreyschafer@gmail.com
1   john      johncena@gmai;.com

In [193]:
df.loc[[0],['first','last']]

   first     last
0  corey  schafer

In [194]:
df.loc[len(df)] = ['Roman','cena','Romancena@gmail.com']
df

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com
3  Roman     cena     Romancena@gmail.com

NOW  USING CONCEPTS OF FILTERING

In [195]:
df['last'] == 'cena' # to check whether cena is the. last name or not , if the answer is true then is yes , or not is false

0    False
1     True
2    False
3     True
Name: last, dtype: bool

In [196]:
filt = (df['last']== 'cena') # created a varible as filt . instead of filter becoz 'filter' is python built in function

In [197]:
df[filt]

   first  last                email
1   john  cena   johncena@gmai;.com
3  Roman  cena  Romancena@gmail.com

In [198]:
df.loc[filt,'email'] # now we can get any info. of elements having last = cena .

1     johncena@gmai;.com
3    Romancena@gmail.com
Name: email, dtype: str

In [199]:
# let if we want first name = john and last name = cena then 
filt1 = (df['last'] == 'cena') & (df['first'] == 'john') # using AND (&) 
df[filt1]

  first  last               email
1  john  cena  johncena@gmai;.com

In [200]:
# using OR(|)
filt2 = (df['last'] =='cena') | (df['first'] =='corey')
df[filt2]

   first     last                   email
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
3  Roman     cena     Romancena@gmail.com

In [201]:
df.loc[~filt2,'email'] # ~filt2 will gives out ouputs of elements other than which full filled this conditions

2    harrypotter@gmail.com
Name: email, dtype: str

LECTURE 05 - Updating Rows & Columns - modifying data within dataframes

In [202]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [205]:
df.columns = ['first_name','last_name','email']
df.columns

Index(['first_name', 'last_name', 'email'], dtype='str')

In [208]:
# to convert coulumns into uppercase 
df.columns = [x.upper() for x in df.columns]
df

  FIRST_NAME LAST_NAME                   EMAIL
0      corey   schafer  coreyschafer@gmail.com
1       john      cena      johncena@gmai;.com
2      harry    potter   harrypotter@gmail.com
3      Roman      cena     Romancena@gmail.com

In [ ]:
# to replaces spaces with _ . for example if there is a coloumn name first name , then df. first name will show and error message 
# so we need to add _ b/w them for example first_name
df.columns = df.columns.str.replace(' ','_') # it will convert spaces into _
df

  FIRST_NAME LAST_NAME                   EMAIL
0      corey   schafer  coreyschafer@gmail.com
1       john      cena      johncena@gmai;.com
2      harry    potter   harrypotter@gmail.com
3      Roman      cena     Romancena@gmail.com

In [214]:
# what if  we we wanted to do some changes in specific columns 
# let we wanted to change first_name and last_name as first and last
df.rename(columns={'FIRST_NAME': 'first' , 'LAST_NAME':'last'}, inplace=True)
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com
3  Roman     cena     Romancena@gmail.com

In [216]:
# UPDATING DATA IN A ROWS 
df.loc[3] = ['Roman','reings','romanreings@gmail.com']
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com
3  Roman   reings   romanreings@gmail.com

In [222]:
# lets again we wanted to change the name roman reings as roman cena 
df.loc[3,[ 'last','EMAIL']]  = ['cena','romancena@gmail.com']
df

   first     last                   EMAIL                email
0  corey  schafer  coreyschafer@gmail.com                  NaN
1   john     cena      johncena@gmai;.com                  NaN
2  harry   potter   harrypotter@gmail.com                  NaN
3  Roman     cena     romancena@gmail.com  romancena@gmail.com

In [230]:
df.loc[2,'last'] = 'wonder'
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   wonder   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

In [231]:
# Alternate method by using at
df.at[2,'last'] = 'potter'
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry   potter   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

In [233]:
filt = (df['EMAIL'] == 'harrypotter@gmail.com')
df[filt]

   first    last                  EMAIL
2  harry  potter  harrypotter@gmail.com

In [234]:
# IS WE WANT TO ACESSS ONLY LAST NAME THEN WE CAN DO LIKE 
filt = (df['EMAIL'] == 'harrypotter@gmail.com')
df[filt]['last']

2    potter
Name: last, dtype: str

In [ ]:
# trying to update single row of data 
filt = (df['EMAIL'] == 'harrypotter@gmail.com')
df[filt]['last'] = ['kane']

/var/folders/81/0vymtr1s7xz06fvcc28tzjsw0000gn/T/ipykernel_7329/3055680896.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[filt]['last'] = ['kane']

In [237]:
# so to fix the above error we have to use loc function 
filt = (df['EMAIL'] == 'harrypotter@gmail.com')
df.loc[filt,'last'] = ['kane']
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry     kane   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

In [240]:
# updating multiple row of data 
# let convert all tge emails to lowercase 

df['EMAIL'] = df['EMAIL'].str.lower()
df

   first     last                   EMAIL
0  corey  schafer  coreyschafer@gmail.com
1   john     cena      johncena@gmai;.com
2  harry     kane   harrypotter@gmail.com
3  Roman     cena     romancena@gmail.com

apply.    
map.    
applymap.    
replace.

apply: Runs a function element-wise on a Series, or axis-wise on a DataFrame.

map: Swaps out specific values in a Series using a lookup dictionary.

applymap: Runs a function on every single individual element across an entire DataFrame.

replace: Swaps values in a Series without accidentally wiping out unmapped fields.

In [ ]:
# apply

In [241]:
df['EMAIL'].apply(len)

0    22
1    18
2    21
3    19
Name: EMAIL, dtype: int64

In [245]:
def update_email(EMAIL):
    return EMAIL.UPPER
df['EMAIL'] = df['EMAIL'].apply(update_email)

AttributeError: 'str' object has no attribute 'UPPER'